{% set name = "pyvcd" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 285fcd96c3ee482e7b222bdd01d5dd19c2f5a0ad9b8e950baa98d386a2758c8f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - six

test:
  imports:
    - vcd

about:
  home: https://pypi.org/project/pyvcd
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'The PyVCD package writes Value Change Dump (VCD) files as specified in IEEE 1364-2005.'

  doc_url: http://pyvcd.readthedocs.io/en/latest/
  dev_url: https://github.com/SanDisk-Open-Source/pyvcd

extra:
  recipe-maintainers:
    - TimSnyder
