{% set name = "pyvcd" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96e3c7b9409e63f58eb4b5c22b017f9f3412ddbdfc734cec2e1dfad5c29a83df

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv_build>=0.9.13,<1.0
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - vcd

about:
  home: https://pypi.org/project/pyvcd
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The PyVCD package writes Value Change Dump (VCD) files as specified in IEEE 1364-2005.

  doc_url: http://pyvcd.readthedocs.io/en/latest/
  dev_url: https://github.com/SanDisk-Open-Source/pyvcd

extra:
  recipe-maintainers:
    - TimSnyder
    - davidbrochart
