travis:
  secure:
    BINSTAR_TOKEN: dFPGmCw7c/+QBaIMSbi6aRSNjE6HIZG3I/27+hNhMsQT9YwYkqEZf/UUwTrVOjM7ZKQbK67m7PYNEhP1KkL4CEv8URmJNqc3GY8jW+FHNG/fcwAgZKm1VG9L6mExI/Mn8p+qIyDCFjyJhu5L8zOHSK7W1+lU5k+XvTv3YqPKaslQ40l9rEwWGhtMNFR5Pme85tMSFSZkrT0B1e7sqG5EJYSlFhKm3nWEGjwOCzTa21brP7+Zd6qfC2R/ZHE6e4/hDcJXJsLivWFqun+qQjMBhgxJAPqrn1WQ4WAKBhfsNcXrviXxp0AGjwFY22Cx6UNGnrZYsVkbts4wjVMKE6lmyrQ+oK2KsKkQYQURhcvSBwuswnuSpxPgvwoPnkTtM2i8UmUuN4XeeeP3Z+y5ByTHJNfhtBMnf8+pE8RybkE0zxW3CJ1ZEqi0KJGWBWpSPW9OZKdQGxQ4jupDDesI6jHE4Ibn5LMd/IAPx1iGMlMy58dqn7zOBvyDHGT/zywHiogqBtnPVLuC0fEKgLLu5whk4VgPu9aR604/LIKZ87wF95LBGxJANTyrK0x0XzkOUW8juFAvcOnJx267sA71AueulEdBnTbIht165pUjJB49h2kM8qIclXxX+TOlNXR+08Y2hoZDd80P0ZeiXchmuO7bMjmIqI/kpiKCA1DdKRzM/Wk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
